# Generated by Django 3.1.4 on 2020-12-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='lname',
            new_name='last_name',
        ),
    ]
